[package]
name = "authority_manage"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bincode = "0.8.0"
cita-types = { path = "../cita-types" }
