[package]
name = "pubsub_zeromq"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies.zmq]
version = "0.8"
default-features = false
features = []

[dependencies]
lazy_static = "1.2.0"
logger = { path = "../logger" }
