[package]
name = "util"
version = "0.6.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
parking_lot = "0.10.0"
ansi_term = "0.12.1"
serde = "1.0.103"
toml = "0.5.5"
git2 = "0.10.2"
rustc_version = "0.2.3"
backtrace = "0.3.40"
cita-logger = "0.1.1"