[package]
name = "cita-common-benches"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
rand = "0.7.2"

[dev-dependencies]
criterion = "0.3.0"
tiny-keccak = { version = "2.0.1", features = ["keccak"]}
blake2b = { path = "../blake2b" }
secp256k1 = {version = "0.15.0", features = ["rand", "recovery"]}
sodiumoxide = "0.2.5"
libsm = { git = "https://github.com/citahub/libsm", rev = "4d0e6199fca0934c58131de1d0036e9aa4da26c1" }

[[bench]]
name = "hash-algos"
harness = false

[[bench]]
name = "sign-algos"
harness = false
